version: '3.9'

services:
  react-app:
    image: node:latest
    container_name: react-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run dev"
